services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
  
  redis:
    image: redis:8.2.1-alpine
    ports:
      - "6380:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery -A core worker -l info"
    volumes:
      - ./core:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
  
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./core:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:81"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # nginx:
  #   image: nginx:stable
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./core/media:/media
  #     - ./core/staticfiles:/static
  #   restart: always

volumes:
  postgres_data:
  pgadmin_data:
