from django.urls import path

from ..views.restaurants import (
    RestaurantDocumentDetailView,
    MessageTemplateListView,
    RestaurantMenuAllergensView,
    RestaurantMenuDetailView,
    RestaurantMenuListView,
    RestaurantAvailableTablesView,
    RestaurantTableListView,
    RestaurantTableDetailView,
    RestaurantListView,
    RestaurantDetailView,
    RestaurantDocumentListView,
    RestaurantDashboardView,
    RestaurantAnalyticsTopDishesView,
    RestaurantAnalyticsMostVisitedView,
    RestaurantPromotionListView,
)

urlpatterns = [
    path(
        "/<uuid:restaurant_uid>/analytics/most-visited",
        RestaurantAnalyticsMostVisitedView.as_view(),
        name="restaurant.analytics.most-visited",
    ),
    path(
        "/<uuid:restaurant_uid>/analytics/top-dishes",
        RestaurantAnalyticsTopDishesView.as_view(),
        name="restaurant.analytics.top-dishes",
    ),
    path(
        "/<uuid:restaurant_uid>/menu/<uuid:menu_uid>/allergens",
        RestaurantMenuAllergensView.as_view(),
        name="restaurant.menu-allergens",
    ),
    path(
        "/<uuid:restaurant_uid>/promotions",
        RestaurantPromotionListView.as_view(),
        name="restaurant.promotions",
    ),
    path(
        "/<uuid:restaurant_uid>/menu/<uuid:menu_uid>",
        RestaurantMenuDetailView.as_view(),
        name="restaurant.menu-detail",
    ),
    path(
        "/<uuid:restaurant_uid>/menu",
        RestaurantMenuListView.as_view(),
        name="restaurant.menu-list",
    ),
    path(
        "/<uuid:restaurant_uid>/dashboard",
        RestaurantDashboardView.as_view(),
        name="restaurant.dashboard",
    ),
    path(
        "/<uuid:restaurant_uid>/message-templates",
        MessageTemplateListView.as_view(),
        name="restaurant.message-template-list",
    ),
    path(
        "/<uuid:restaurant_uid>/documents/<uuid:document_uid>",
        RestaurantDocumentDetailView.as_view(),
        name="restaurant.document-detail",
    ),
    path(
        "/<uuid:restaurant_uid>/documents",
        RestaurantDocumentListView.as_view(),
        name="restaurant.document-list",
    ),
    path(
        "/<uuid:restaurant_uid>/tables/<uuid:table_uid>",
        RestaurantTableDetailView.as_view(),
        name="restaurant.table-detail",
    ),
    path(
        "/<uuid:restaurant_uid>/tables",
        RestaurantTableListView.as_view(),
        name="restaurant.table-list",
    ),
    path(
        "/<uuid:restaurant_uid>/tables/available",
        RestaurantAvailableTablesView.as_view(),
        name="restaurant.available-tables",
    ),
    path(
        "/<uuid:restaurant_uid>",
        RestaurantDetailView.as_view(),
        name="restaurant.detail",
    ),
    path("", RestaurantListView.as_view(), name="restaurant.list"),
]
